---
apiVersion: v1
kind: Service
metadata:
  namespace: datakart
  name: datakart-webhooks
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  type: ClusterIP
  selector:
    app: datakart-webhooks  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: datakart-webhooks
spec:
  selector:
    matchLabels:
      app: datakart-webhooks
  template:
    metadata:
      labels:
        app: datakart-webhooks
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nodepool
                    operator: In
                    values:
                      - dk2apps
      containers:
        - name: datakart-webhooks
          image: gsone.azurecr.io/gsone-uat/datakart-webhooks:$(Build.BuildId)
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: env-config
          env:
            - name: TRACE_APP_NAME
              value: "datakart-webhooks"
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: gsone-cr

